# Generated by Django 5.1.5 on 2025-01-25 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'labo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Preferes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familleId', models.IntegerField(default=-1)),
                ('modeleId', models.IntegerField(default=-1)),
            ],
            options={
                'db_table': 'preferes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('pref', models.BooleanField()),
                ('labo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.labo')),
            ],
            options={
                'db_table': 'famille',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('pref', models.BooleanField()),
                ('test', models.CharField(default='test', max_length=10)),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.famille')),
            ],
            options={
                'db_table': 'modele',
                'managed': True,
            },
        ),
    ]
