# Generated by Django 5.1.5 on 2025-01-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famille',
            name='pref',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='modele',
            name='pref',
            field=models.IntegerField(default=1),
        ),
    ]
