# Generated by Django 5.1.5 on 2025-01-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_famille_pref_alter_modele_pref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modele',
            name='test',
        ),
    ]
