# Generated by Django 5.1.5 on 2025-02-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_modele_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famille',
            name='pref',
        ),
        migrations.RemoveField(
            model_name='modele',
            name='pref',
        ),
    ]
